### PR TITLE
Center video wrt viewport height

### LINKED ISSUE #43: Video page renders well on chrome but some issues on firefox. Screenshot1[Firefox] , Screenshot2[Chrome]. Control bar is kind of half hidden in firefox
Firefox Render

Chrome Render

### PR DESCRIPTION
**Pull request by xypnox**
The video container/view is always centered vertically in all devices except mobile. This will fix most of the bottom-bar/description out of view errors.

Though this is generally a minor tweak, it may break UI in some cases, thus testing is required.

Fixes #43

### CODE REVIEW

**Comment by xypnox** [comment]
@rava-dosa Can you check if this PR fixes the layout problems that you encountered?

**Review by thescriptninja — APPROVED** [review]
Tested in Chrome and Firefox, works fine in my machine :v:

**Comment by rava-dosa** [comment]
@xypnox  Worked well on both firefox and chrome

**Comment by mukul-mehta** [comment]
Tested on my laptop with both 1920x1080 and 1366x768 settings, works well 👍

**Review by mukul-mehta — APPROVED** [review]

**Review by ghostwriternr — APPROVED** [review]
LGTM!

**Pull request merged**
