### PR TITLE
Reduce code by using type as object key

### PR DESCRIPTION
**Pull request by xypnox**
I have reduced repetitions in places by using the list type instead of branching for every case.

As the server is down at the moment, I can not test whether the code works fine. Though, typescript doesn't throw any errors at the moment.

I am also considering moving the [Fetching of data](https://github.com/lttkgp/falcon/blob/f4a26bb742af496158432c37cf0c6fd0a7ec1a2e/src/views/home.tsx#L13), to the list component itself.

### CODE REVIEW

**Review by ghostwriternr — APPROVED** [review]
Sweet! This works.

**Comment by ghostwriternr** [comment]
> I am also considering moving the Fetching of data, to the list component itself.

This should be fine too, although I like it being in `Home` as an explicit indication of the action being performed when navigating to the home page as opposed to keeping it in the component logic (which also makes it less re-usable in general, although we don't have other use cases to back this claim yet).

**Comment by xypnox** [comment]
Also, I have reordered imports in all of the files (that I could find). 

The order for imports is:

```js
// list.tsx used here as an example

// React and library Imports (except icons and visual only imports)
import React from "react";
import { useDispatch, useSelector } from "react-redux";
import styled from "styled-components";

// Redux Tooling and Utility functions
import { Post, FeedListType } from "../store/list/types";
import { getSongList } from "../store/list/effects";
import { FalconRootState } from "../store/rootReducer";
import { filterUniqueVideos } from "../utils";

// Components
import Card from "./card";
import Button from "./button";

// Icons/CSS/SVG/Image Imports (Visual/Style related)
import { ChevronRight, ChevronLeft, Shuffle } from "react-feather";
```

Each of these "blocks" is separated by a single line. Suggestions are welcome.

A minor inconvenience of this would be that the some of the redux tooling is in the library whereas some we implement ourselves. These are separated differently as the first block contains all the libraries.

Would it be better to move redux imports to the second block?

The only advantage of such imports is cleaner code and faster recognition. Also, it avoids importing things in different ways from a library, for example, while reordering the imports, I discovered that the some icons from react feather were imported as `Icon` and other icons as their unique names. Following this import structure would reduce these inconsistencies.

**Comment by ghostwriternr** [comment]
In general, I'm always leaning towards sorting imports in logical blocks, so it is a +1 from me. From the perspective of this being OSS though, I'd prefer this to be automated rather than put the onus (and potential back and forth during reviews) on a contributor to do this. I love the ESLint [`sort-imports`](https://eslint.org/docs/rules/sort-imports) rule that does exactly this. Extending ESLint for CRA apps is quite easy, so you can give it a shot.

> A minor inconvenience of this would be that the some of the redux tooling is in the library whereas some we implement ourselves. These are separated differently as the first block contains all the libraries.
Would it be better to move redux imports to the second block?

I'd prefer not mixing library imports with local imports. Having framework-specific import blocks seems overkill and doesn't add much value (also can't be automated using tools like ESLint above).

**Comment by xypnox** [comment]
I made the classic mistake of doing something for which a library already exists XD.

I will check the `sort-imports` out and configure it for eslint. I think `sort-imports` can't differentiate between utility functions and components. Also, It just sorts imports by the way we have used the import syntax without much context of how we group it. 

It may be possible to create a plugin that does exactly that, where we can define keywords or regex patterns which can be folder names libraries etc that can be grouped together in blocks as demoed earlier.

**Comment by xypnox** [comment]
Found this though: https://dev.to/otamnitram/sorting-your-imports-correctly-in-react-213m which should do the job as well.

**Comment by xypnox** [comment]
I checked the deploy preview and it is working as expected. I am merging this.

cc. @ghostwriternr

**Pull request merged**
