### PR TITLE
Mobile view fixes optimizations

### PR DESCRIPTION
**Pull request by xypnox**
Mobile views have been fixed. 
Screen Shot 2020-05-09 at 14 52 35
Screen Shot 2020-05-09 at 14 52 45
Screen Shot 2020-05-09 at 14 53 13

Note:
For accurate testing of the mobile view, either use a physical smartphone or set the device to a phone in mobile view for desktop browsers.

### CODE REVIEW

**Comment by xypnox** [comment]
Looks sick when installed as a PWA.
Screenshot_20200509-150724

**Comment by xypnox** [comment]
Hi,

- I have added the inline attribute, can you test and confirm if it works?

- I have shrunk the card so it only shows Title and Channel with controls to change the song. The full view comes up when scrolling to the top.

**Comment by ghostwriternr** [comment]
Love the updated card! Looks pretty sweet now.
There's some new weirdness with the dark mode though :/ And the full sized card still doesn't appear after scrolling back to top.
Screen capture: https://imgur.com/a/mrxe1HG

**Comment by ghostwriternr** [comment]
Same issues on Firefox on iOS too (but that's not too surprising since all browsers on iOS are forced to use WebKit, same as Safari).
And forgot to mention, the video player inline fix works great!

**Pull request merged**
