### PR TITLE
Bug fixes and responsiveness 1

### LINKED ISSUE #23: Artist name and some genres are hidden
Artist name and some genres are hidden when the song name crosses into the next line or the viewport dimensions are not large enough.

fsvdbgbdvhrtdv

> Screenshot & reported by @thescriptninja

### LINKED ISSUE #24: Remove search input placeholder
The search feature is intended for a later version. Thus, the placeholder should be hidden for now.

### PR DESCRIPTION
**Pull request by xypnox**
This PR fixes a few bugs including:

- [x] Hiding the search-bar (which will be added as a feature for later releases) #24 
- [x] Fix the header widths and alignments of different titles so everything is left aligned perfectly.
- [x] Make the title and artist text in description overflow hidden in the video description. #23 
    - For those who would like to view the full name etc can visit the video on Youtube, I also plan to add hover-text to display these. But IMO it will unnecessarily complicate the codebase and would not be a feature a regular user would use often.

Here is a  screenshot of the clipped title in work:

Screenshot_2020-06-23 LTTKGP 🎶 🎶 🎶(1)

---

Fixes #23 
Fixes #24

### CODE REVIEW

**Comment by xypnox** [comment]
Builds on my machine :man_shrugging:

**Comment by xypnox** [comment]
Ah the warnings are considered as errors in build scripts :disappointed:

**Comment by mukul-mehta** [comment]
I believe it would be a good idea to pick default theme from system settings, could we do that as well?

**Comment by xypnox** [comment]
> Can you also store the current theme (light/dark) to localStorage and use that on start? The setting gets reset every time otherwise.

Yes I can, but I don't know if this is counted as a cookie situation which will result in the necessity of adding the **ugly** "By using this site you agree to the cookie policy" and us having to maintain a cookie policy.

I think that querying the default theme from the system preference would be a better idea as it wouldn't add a legal complexity in the mix.

Surely would add this in the next PR.

**Pull request merged**
