### PR TITLE
Bug fixes and improvements

### LINKED ISSUE #20: Scroll to the video if lower in queue
Currently the queue opens at the top even when a song lower in the queue is selected in the list. 

Fix the error by adding the scroll if the current index is not the first video.

### LINKED ISSUE #45: Update title when player moves to the next link
When the LTTKGP tab is unattended and the player moves to the next link, the title updates to the name of the next song only on switching to that tab.

### PR DESCRIPTION
**Pull request by xypnox**
The following bugs have been fixed:

- [x] Title emojis have been "inlined" (They showed up earlier as `[object Object]`) 
- [x] The title update uses `defer=false` so that it updates in background too. #45 (Ref: [1])
- [x] Fixes the scroll to current video when a new video is selected that is not at the top of the queue. #20 
 
Fixes #45 
Fixes #20

[1]: https://github.com/nfl/react-helmet/issues/315

### CODE REVIEW

**Review by thescriptninja — APPROVED** [review]
LGTM! :v:

**Comment by xypnox** [comment]
@thescriptninja Can you check if the title bug fixed? It works for me, but may not work on some other browsers.

**Comment by thescriptninja** [comment]
Checked in Chrome and Firefox. Working fine in both, bug is fixed :+1:

**Review by ghostwriternr — APPROVED** [review]
LGTM! It would be lovely if we can support "load more" in the playlist in the player view too. Right now, the songs just stop playing upon reaching the end.

Fine with having it as a separate PR as well.

**Pull request merged**
