### PR TITLE
Persist user theme through localStorage

### LINKED ISSUE #32: Persist user's theme preference through local storage
> I like this in general! IMO, we should also persist the user preference in localstorage. In cases where I'm someone who uses the OS light mode because it feels better, but would prefer dark mode for websites and specifically, LTTKGP. ( I don't think anyone goes the other way round though :laughing: ) 
> \- @ghostwriternr 

[As requested here](https://github.com/lttkgp/falcon/pull/31#pullrequestreview-442611331)

### PR DESCRIPTION
**Pull request by sahil-shubham**
## Changes

- Made changes in the function `changeTheme` to make it store the theme in the localStorage
- Made a new function `themeChecker` which checks the localStorage for user preference and changes the theme
- Updated README.md with the new function

### CODE REVIEW

**Comment by sahil-shubham** [comment]
Hey, I was a little confused over the case when a user prefers dark theme in the settings, but wants the light theme for websites. But after reading what @ghostwriternr said, I don't think anyone wants it this way. 

What do you think  about this? Should I make a change for cases like these?

**Comment by xypnox** [comment]
@sahil-shubham The code to store the theme preference looks fine.

However, Since both the `themeChecker` and `setThemeOnUserPref` set the theme, it would be better to combine them into a single function that sets the theme. 

The logic for the function can be summed up as follows:

image

So that we first check the localStorage and then the color preference of the user.

Ref: [The Quest for the Perfect Dark Mode](https://joshwcomeau.com/gatsby/dark-mode/)
 
There are other tips and tricks in the above article but for storing and setting the theme in combination with userpreference, the above method should work fine.

**Comment by sahil-shubham** [comment]
@xypnox Thank you for giving me such a detailed explanation on how to proceed. I have unified the `setThemeOnUserPref` and `themeChecker` (typed incorrectly in the commit message). I have tested it locally and it performs according to the image in you comment.

**Review by ghostwriternr — APPROVED** [review]
This is great! Thanks @sahil-shubham and @xypnox  for covering both localstorage and prefer-color-scheme :tada:

**Comment by mukul-mehta** [comment]
@sahil-shubham Thanks for the PR!
@xypnox Thanks for sharing that article, great stuff!

**Pull request merged**
