### PR TITLE
List view

### PR DESCRIPTION
**Pull request by xypnox**
Current list view is something like this:
The list view needs to be made scrollable, and mobile view has to be tweaked.
Screenshot_2020-04-19 🎶 LTTKGP 🎶

- [x] Make list scrollable
- [x] Replace hardcoded data by props
- [x] Make it touch responsive

### CODE REVIEW

**Comment by ghostwriternr** [comment]
Minor UI glitches:
Desktop: Sidebar text overlapping with main content
image

Mobile: Jitters when selecting a tile from the list view. (Is the hover action even needed on mobile?)
IMG_6135

**Comment by xypnox** [comment]
Oh well I have to test this for all screen sizes, also, I would change the
interaction animations on mobile.

**Comment by xypnox** [comment]
@ghostwriternr The latest commit fixes most of the issues with responsiveness, only the scrolling on desktop needs to be implemented.

**Comment by xypnox** [comment]
@ghostwriternr The PR is now ready for review!

**Comment by xypnox** [comment]
Yep, to get around that I would have to track on every scroll, however, currently it is intended that the desktop users scroll through the button and the mobile through dragging.

How did you scroll manually? Are the scrollbars visible?

**Comment by ghostwriternr** [comment]
I'm just scrolling horizontally with my laptop trackpad.

**Comment by xypnox** [comment]
I think this fix works, can you confirm?

**Comment by ghostwriternr** [comment]
Same scroll behaviour : /

**Comment by xypnox** [comment]
Browser, OS?

**Comment by ghostwriternr** [comment]
https://photos.app.goo.gl/tXf4EpmLt8EnDfjY6

Firefox Dev Edition v76.0, MacOS Mojave 10.14.6

**Comment by xypnox** [comment]
Does the arrow appear after stopping the scroll?

**Comment by ghostwriternr** [comment]
Nope...

**Comment by xypnox** [comment]
Perhaps would look into it tomorrow  zzZ

**Comment by xypnox** [comment]
@ghostwriternr I have fixed the bug, can you check if it works now?

**Pull request merged**
